### ISSUE TITLE
DiscordHandler::write not compatable with Monolog\Handler\AbstractProcessingHandler::write

### ISSUE THREAD

**Issue by ThePoet444** [lefuturiste/monolog-discord-handler#5]
```Declaration of DiscordHandler\DiscordHandler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void in ~/lefuturiste/monolog-discord-handler/src/DiscordHandler.php on line 153.```

I'm also running laravel 6, which uses monolog 2 I believe. Which is probably the problem, but I would love to see if this can get updated. It's very useful.

**Comment by lefuturiste** [comment]
OK thanks I will check that

**Comment by lefuturiste** [comment]
Compatibility with version 2 of monolog fixed in version 0.3. You can now update the lib.
with the commit fd2909c065c61700e6def4ad4f85da87be462bba
not compatible anymore with older version of PHP than 7.2

If you have any issues let me known here!
