### ISSUE TITLE
Error on fresh install of monolog and this project

### ISSUE THREAD

**Issue by bobvmierlo** [lefuturiste/monolog-discord-handler#8]
`Fatal error: Declaration of DiscordHandler\DiscordHandler::write(array $record): void must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): void in C:\xampp\htdocs\logger\vendor\lefuturiste\monolog-discord-handler\src\DiscordHandler.php on line 77`

Using monolog 3.3.1 and monolog-discord-handler 0.3.1

**Comment by lefuturiste** [comment]
Thanks for this report, I will take a look at this.

**Comment by bobvmierlo** [comment]
#9 should fix this

**Comment by lefuturiste** [comment]
Should be fixed in 0.4
